version: '2'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /opt/traefik/traefik.config.toml:/etc/traefik/traefik.config.toml
      - /opt/traefik/certs/:/etc/traefik/certs/
    container_name: traefik
    restart: always

networks:
  web:
    external: true
