[tls]
  #[[tls.certificates]]
  #  certFile = "/etc/traefik/certs/cert.crt"
  #  keyFile = "/etc/traefik/certs/cert.key"

  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/certs/cert.crt"
        keyFile = "/etc/traefik/certs/cert.key"
